spring.application.name=stock-api


# 로컬 개발 시 활성화
# spring.profiles.active=local

# 기본 프로필 (배포 환경)
spring.profiles.active=prod

# Render 등 클라우드 배포 시 환경 변수로 설정 가능
# SPRING_PROFILES_ACTIVE=prod

# JVM 힙 메모리 제한 (Render Free 메모리 최적화)
# JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m(render 무료버전용 메모리)


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true