spring.application.name=stock-api


# 로컬
#spring.profiles.active=local

# 테스트
spring.profiles.active=prod

#배포시에는 환경변수에
# SPRING_PROFILES_ACTIVE=prod

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true