spring.application.name=stock-api


# 로컬 개발 시 활성화
# spring.profiles.active=local

# 기본 프로필 (배포 환경)
spring.profiles.active=prod

# Render 등 클라우드 배포 시 환경 변수로 설정 가능
# SPRING_PROFILES_ACTIVE=prod


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true